ENABLED_COMPILERS = clang clang_O2 clang_pic gcc gcc_O2 gcc_pic
LIFT_ARTEFACTS_clang := $(COMMON_ARTEFACTS) $(BAP_ARTEFACTS)
LIFT_ARTEFACTS_clang_pic := $(COMMON_ARTEFACTS) $(BAP_ARTEFACTS)
LIFT_ARTEFACTS_gcc := $(COMMON_ARTEFACTS) $(BAP_ARTEFACTS)
LIFT_ARTEFACTS_gcc_O2 := $(COMMON_ARTEFACTS) $(BAP_ARTEFACTS)
LIFT_ARTEFACTS_gcc_pic := $(COMMON_ARTEFACTS) $(BAP_ARTEFACTS)
