
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Examples 

on:
  push:
    paths: src/**

permissions:
  contents: read

runs: 
  using: 'docker'
  image: 'docker/asli.Dockerfile'
  args: 
    - ./lift.sh examples/arrays/arrays.c /examples-arrays.adt /example-arrays.elf


