name: Scala Compile and Test 

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  basil-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Compile Jar
      run: sbt assembly
    - name: Run tests
      timeout-minutes: 10
      run: sbt test
